[workspace]
channels = ["conda-forge"]
name = "cuda-python-repro"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
isort = ">=6.0.1,<7"
autopep8 = ">=2.3.2,<3"

[pypi-dependencies]
torch = "*"
torchvision = "*"

[feature.cu13.dependencies]
cuda-toolkit = ">=13.0.0,<14"
cuda-python = ">=13.0.0,<14"

[feature.cu12.dependencies]
cuda-toolkit = ">=12.0.0,<13"
cuda-python = ">=12.0.0,<13"

[feature.cu13.pypi-options]
index-url = "https://download.pytorch.org/whl/cu130"

[feature.cu12.pypi-options]
index-url = "https://download.pytorch.org/whl/cu129"

[environments]
cu12 = { features = ["cu12"] }
cu13 = { features = ["cu13"] }
