[workspace]
channels = ["conda-forge"]
name = "cuda-python-repro"
platforms = ["linux-64"]
version = "0.1.0"

[system-requirements]
cuda = "12.9"

[tasks]

[dependencies]
cuda-toolkit = ">=12.9.0,<13"
cuda-python = ">=12.9.0,<13"
pytorch-gpu = ">=2.7.0,<3"
isort = ">=6.0.1,<7"
autopep8 = ">=2.3.2,<3"
